CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255),
  google_sub varchar(255),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  purchase_price numeric(12, 2) NOT NULL CHECK (purchase_price >= 0),
  selling_price numeric(12, 2) NOT NULL CHECK (selling_price >= 0),
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  barcode varchar(100)
);

CREATE UNIQUE INDEX IF NOT EXISTS products_user_id_name_key
  ON products (user_id, LOWER(name));

CREATE TABLE IF NOT EXISTS stock_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quantity integer NOT NULL CHECK (quantity <> 0),
  description varchar(500),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_name varchar(255) NOT NULL,
  phone varchar(50),
  notes varchar(500),
  balance numeric(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_id integer REFERENCES customers(id) ON DELETE RESTRICT,
  total numeric(12, 2) NOT NULL CHECK (total >= 0),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity integer NOT NULL CHECK (quantity > 0),
  purchase_price numeric(12, 2) NOT NULL CHECK (purchase_price >= 0),
  selling_price numeric(12, 2) NOT NULL CHECK (selling_price >= 0),
  discount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (discount >= 0)
);

CREATE TABLE IF NOT EXISTS transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_id integer NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  debit numeric(12, 2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit numeric(12, 2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
  note varchar(500)
);

CREATE INDEX IF NOT EXISTS products_user_id_idx ON products(user_id);
CREATE INDEX IF NOT EXISTS stock_history_user_id_idx ON stock_history(user_id);
CREATE INDEX IF NOT EXISTS customers_user_id_idx ON customers(user_id);
CREATE INDEX IF NOT EXISTS invoices_user_id_idx ON invoices(user_id);
CREATE INDEX IF NOT EXISTS transactions_user_id_idx ON transactions(user_id);

