-- Accounting App - Complete Supabase/PostgreSQL schema
-- Run this entire file in the Supabase SQL Editor.
-- It is safe to run more than once and does not delete existing data.

BEGIN;

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  email varchar(255) NOT NULL,
  password_hash varchar(255),
  google_sub varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
  CONSTRAINT users_login_method_check CHECK (
    password_hash IS NOT NULL OR google_sub IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key
  ON public.users (lower(email));

CREATE UNIQUE INDEX IF NOT EXISTS users_google_sub_unique
  ON public.users (google_sub)
  WHERE google_sub IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  name varchar(255) NOT NULL,
  purchase_price numeric(12, 2) NOT NULL,
  selling_price numeric(12, 2) NOT NULL,
  stock_quantity integer NOT NULL DEFAULT 0,
  barcode varchar(100),
  CONSTRAINT fk_products_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT products_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT products_purchase_price_check CHECK (purchase_price >= 0),
  CONSTRAINT products_selling_price_check CHECK (selling_price >= 0),
  CONSTRAINT products_stock_quantity_check CHECK (stock_quantity >= 0),
  CONSTRAINT products_barcode_not_blank CHECK (
    barcode IS NULL OR btrim(barcode) <> ''
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS products_user_id_name_key
  ON public.products (user_id, lower(name));

CREATE UNIQUE INDEX IF NOT EXISTS products_user_id_barcode_key
  ON public.products (user_id, barcode)
  WHERE barcode IS NOT NULL;

CREATE INDEX IF NOT EXISTS products_user_id_idx
  ON public.products (user_id);

CREATE TABLE IF NOT EXISTS public.stock_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  user_id integer NOT NULL,
  quantity integer NOT NULL,
  description varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_stock_history_product
    FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE,
  CONSTRAINT fk_stock_history_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT stock_history_quantity_check CHECK (quantity <> 0)
);

CREATE INDEX IF NOT EXISTS stock_history_user_id_idx
  ON public.stock_history (user_id);

CREATE INDEX IF NOT EXISTS stock_history_product_id_idx
  ON public.stock_history (product_id);

CREATE INDEX IF NOT EXISTS stock_history_user_created_at_idx
  ON public.stock_history (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  customer_name varchar(255) NOT NULL,
  phone varchar(50),
  notes varchar(500),
  balance numeric(12, 2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_customers_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT customers_name_not_blank CHECK (btrim(customer_name) <> '')
);

CREATE INDEX IF NOT EXISTS customers_user_id_idx
  ON public.customers (user_id);

CREATE INDEX IF NOT EXISTS customers_user_name_idx
  ON public.customers (user_id, lower(customer_name));

CREATE TABLE IF NOT EXISTS public.invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  customer_id integer,
  total numeric(12, 2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_invoices_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT fk_invoices_customer
    FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT,
  CONSTRAINT invoices_total_check CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS invoices_user_id_idx
  ON public.invoices (user_id);

CREATE INDEX IF NOT EXISTS invoices_customer_id_idx
  ON public.invoices (customer_id);

CREATE INDEX IF NOT EXISTS invoices_user_created_at_idx
  ON public.invoices (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.invoice_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity integer NOT NULL,
  purchase_price numeric(12, 2) NOT NULL,
  selling_price numeric(12, 2) NOT NULL,
  discount numeric(12, 2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_invoice_items_invoice
    FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE,
  CONSTRAINT fk_invoice_items_product
    FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT,
  CONSTRAINT invoice_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT invoice_items_purchase_price_check CHECK (purchase_price >= 0),
  CONSTRAINT invoice_items_selling_price_check CHECK (selling_price >= 0),
  CONSTRAINT invoice_items_discount_check CHECK (discount >= 0),
  CONSTRAINT invoice_items_discount_limit_check CHECK (
    discount <= quantity * selling_price
  )
);

CREATE INDEX IF NOT EXISTS invoice_items_invoice_id_idx
  ON public.invoice_items (invoice_id);

CREATE INDEX IF NOT EXISTS invoice_items_product_id_idx
  ON public.invoice_items (product_id);

CREATE TABLE IF NOT EXISTS public.transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  customer_id integer NOT NULL,
  invoice_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  debit numeric(12, 2) NOT NULL DEFAULT 0,
  credit numeric(12, 2) NOT NULL DEFAULT 0,
  note varchar(500),
  CONSTRAINT fk_transactions_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT fk_transactions_customer
    FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_transactions_invoice
    FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE,
  CONSTRAINT transactions_debit_check CHECK (debit >= 0),
  CONSTRAINT transactions_credit_check CHECK (credit >= 0),
  CONSTRAINT transactions_amount_check CHECK (
    (debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS transactions_invoice_id_key
  ON public.transactions (invoice_id)
  WHERE invoice_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS transactions_user_id_idx
  ON public.transactions (user_id);

CREATE INDEX IF NOT EXISTS transactions_customer_id_idx
  ON public.transactions (customer_id);

CREATE INDEX IF NOT EXISTS transactions_user_created_at_idx
  ON public.transactions (user_id, created_at DESC);

-- Used by express-session/connect-pg-simple for server-side login sessions.
CREATE TABLE IF NOT EXISTS public.user_sessions (
  sid varchar NOT NULL PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) without time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS user_sessions_expire_idx
  ON public.user_sessions (expire);

-- Used by the Node migration runner to record applied migration files.
CREATE TABLE IF NOT EXISTS public.schema_migrations (
  filename text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- The application connects directly as the database owner. Blocking Supabase's
-- public API roles prevents accidental access through the generated Data API.
REVOKE ALL ON TABLE public.users FROM anon, authenticated;
REVOKE ALL ON TABLE public.products FROM anon, authenticated;
REVOKE ALL ON TABLE public.stock_history FROM anon, authenticated;
REVOKE ALL ON TABLE public.customers FROM anon, authenticated;
REVOKE ALL ON TABLE public.invoices FROM anon, authenticated;
REVOKE ALL ON TABLE public.invoice_items FROM anon, authenticated;
REVOKE ALL ON TABLE public.transactions FROM anon, authenticated;
REVOKE ALL ON TABLE public.user_sessions FROM anon, authenticated;
REVOKE ALL ON TABLE public.schema_migrations FROM anon, authenticated;

COMMIT;
